### ISSUE TITLE
[Request] Remove REPORT COMPLETE from output

### ISSUE THREAD

**Issue by himynameisdave** [JamieMason/eslint-formatter-git-log#2]
## Description

I think it should behave more like the standard ESLint formatter, and by that I mean remove the **REPORT COMPLETE** from the bottom of the output. I don't particularly find the information here particularly useful, and it just adds extra noise.

![image](https://user-images.githubusercontent.com/4298089/65001581-dfa6d680-d8a4-11e9-96e6-636afc6cd0a8.png)

## Suggested Solution

Either remove it entirely, or at least have it default to not being on. We could have an option to display if folks want it. Should be opt-in though (IMO).

## Help Needed

I'm happy to help this by creating PR, I just need to know what the best solution is.

---

Great formatter, this is a really cool tool. 👍 Currently only using it in one repo, but plan on using it in many more.

**Comment by JamieMason** [comment]
Released in [0.6.4](https://github.com/JamieMason/eslint-formatter-git-log/releases/tag/0.6.4) (only took 2 years, 7 months) 😄 )
